version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "ðŸ“¦ [Install Phase] ì˜ì¡´ì„± ì„¤ì¹˜ ì‹œìž‘"
      - cd frontend
      - npm ci
      - echo "âœ… [Install Phase] ì™„ë£Œ"

  pre_build:
    commands:
      - echo "âš™ï¸ [Pre Build Phase] í™˜ê²½ ë³€ìˆ˜ ìƒì„±"
      - echo "VITE_API_HOST=https://festabook.app/api" > .env.production
      - echo "âœ… [Pre Build Phase] ì™„ë£Œ"

  build:
    commands:
      - echo "ðŸš€ [Build Phase] Vite ë¹Œë“œ ì‹œìž‘"
      - npx vite build
      - echo "âœ… [Build Phase] ë¹Œë“œ ì„±ê³µ"

artifacts:
  base-directory: frontend
  files:
    - 'dist/**/*'

cache:
  paths:
    - frontend/node_modules/**/*
