name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
version-template: $MAJOR.$MINOR.$PATCH

categories:
  - title: "🚀 기능 추가"
    labels:
      - "Feat"
  - title: "⚙️ 기능 개선"
    labels:
      - "Refactor"
  - title: "🐛 버그 수정"
    labels:
      - "Fix"
  - title: "🧰 그 외"
    labels:
      - "Chore"
      - "CI/CD"
      - "Docs"
      - "Build"
      - "Common"
      - "Test"

version-resolver:
  major:
    labels:
      - "Major"
  minor:
    labels:
      - "Minor"
  patch:
    labels:
      - "Patch"
  default: minor

exclude-labels:
  - "Release"

change-template: "- $TITLE (#$NUMBER) - @$AUTHOR"
change-title-escapes: '\<*_&'

template: |
  ## ✨ 변경 사항
  $CHANGES

  ## 📦 전체 변경 이력
  [$PREVIOUS_TAG...v$RESOLVED_VERSION](https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION)
