version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo "========== Install Phase =========="
      - cd backend
      - chmod +x ./gradlew

  pre_build:
    commands:
      - echo "========== Pre Build Phase =========="
      - mkdir -p backend/src/main/resources/firebase
      - echo "$APPLICATION_SECRET_YML" > backend/src/main/resources/application-secret.yml
      - echo "$FIREBASE_KEY" > backend/src/main/resources/firebase/firebase-adminsdk-account.json

  build:
    commands:
      - echo "========== Build Phase =========="
      - ./gradlew clean build -x test

  post_build:
    commands:
      - echo "========== Post Build Phase =========="
      - BUILD_JAR=$(find build/libs -name "*.jar" ! -name "*plain.jar" | head -n 1)
      - echo "Build JAR located at: $BUILD_JAR"
      - mkdir -p ../infra/output
      - cp $BUILD_JAR ../infra/output/
      - cp ../infra/appspec.yml ../infra/output/
      - cp -r ../infra/scripts ../infra/output/

artifacts:
  files:
    - infra/output/**/*
