version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo "âš™ï¸ [Setup Phase] ë¹Œë“œ í™˜ê²½ ì¤€ë¹„ ì‹œìž‘"
      - cd backend
      - chmod +x ./gradlew
      - echo "âœ… [Setup Phase] ì™„ë£Œ"

  pre_build:
    commands:
      - echo "âš™ï¸ [Pre Build Phase] í™˜ê²½íŒŒì¼ ìƒì„± ì‹œìž‘"
      - mkdir -p src/main/resources/firebase
      - echo "$SECRET_YML" | base64 -d > src/main/resources/application-secret.yml
      - echo "$FIREBASE_ADMINSDK_ACCOUNT_KEY" > src/main/resources/firebase/firebase-adminsdk-account.json
      - echo "âœ… [Pre Build Phase] ì™„ë£Œ"

  build:
    commands:
      - echo "ðŸš€ [Build Phase] Gradle ë¹Œë“œ ì‹œìž‘"
      - ./gradlew clean build -x test
      - echo "âœ… [Build Phase] ë¹Œë“œ ì„±ê³µ"

  post_build:
    commands:
      - echo "ðŸ“¤ [Post Build Phase] ì‚°ì¶œë¬¼ íŒ¨í‚¤ì§• ì‹œìž‘"
      - BUILD_JAR=$(find build/libs -name "*.jar" -not -name "*plain.jar" | head -n 1)
      - echo "ðŸ“Œ Build JAR located at - $BUILD_JAR"
      - mkdir -p infra/output
      - cp "$BUILD_JAR" infra/output/
      - cp infra/start.sh infra/output/
      - cp infra/appspec.yml ../appspec.yml
      - echo "âœ… [Post Build Phase] ì™„ë£Œ"

artifacts:
  files:
    - backend/infra/output/**/*
    - appspec.yml

cache:
  paths:
    - '/root/.gradle/caches/**/*'
    - '/root/.gradle/wrapper/**/*'
