version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo "ðŸ“¦ [Install Phase] ì˜ì¡´ì„± ì„¤ì¹˜ ì‹œìž‘"
      - cd backend
      - chmod +x ./gradlew
      - echo "âœ… [Install Phase] ì™„ë£Œ"

  pre_build:
    commands:
      - echo "âš™ï¸ [Pre Build Phase] í™˜ê²½íŒŒì¼ ìƒì„± ì‹œìž‘"
      - mkdir -p src/main/resources/firebase
      - echo "$SECRET_YML" > src/main/resources/application-secret.yml
      - echo "$FIREBASE_ADMINSDK_ACCOUNT_KEY" > src/main/resources/firebase/firebase-adminsdk-account.json
      - echo "âœ… [Pre Build Phase] ì™„ë£Œ"

  build:
    commands:
      - echo "ðŸš€ [Build Phase] Gradle ë¹Œë“œ ì‹œìž‘"
      - cd backend
      - ./gradlew clean build -x test
      - echo "âœ… [Build Phase] ë¹Œë“œ ì„±ê³µ"

  post_build:
    commands:
      - echo "ðŸ“¤ [Post Build Phase] ì‚°ì¶œë¬¼ íŒ¨í‚¤ì§• ì‹œìž‘"
      - cd backend
      - BUILD_JAR=$(find build/libs -name "*.jar" -not -name "*plain.jar" | head -n 1)
      - echo "ðŸŽ¯ Build JAR located at - $BUILD_JAR"
      - mkdir -p ../infra/output
      - cp "$BUILD_JAR" ../infra/output/
      - cp ../infra/appspec.yml ../infra/output/
      - cp -r ../infra/scripts ../infra/output/
      - echo "âœ… [Post Build Phase] ì‚°ì¶œë¬¼ íŒ¨í‚¤ì§• ì™„ë£Œ"

artifacts:
  files:
    - backend/infra/output/**/*
