server:
  port: 80
  servlet:
    context-path: /api
  shutdown: graceful
  forward-headers-strategy: native
  tomcat:
    mbeanregistry:
      enabled: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/festabook
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    url: jdbc:mysql://localhost:3306/festabook
    user: root
    password: 1234
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true
  application:
    name: festabook
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
  profiles:
    include: secret
  lifecycle:
    # WAS 종료 대기 시간 15초로 설정
    timeout-per-shutdown-phase: 15s
  servlet:
    # multipart 요청 최대 크기 설정
    multipart:
      max-file-size: 10MB
      max-request-size: 11MB


storage:
  image:
    max-size: 10485760 # 10 * 1024 * 1024, 10MB
    path-prefix: images

# Swagger
springdoc:
  swagger-ui:
    path: /api-docs
    persist-authorization: true
    operations-sorter: method

firebase:
  adminsdk:
    account:
      path: classpath:firebase/firebase-adminsdk-account.json
