spring:
  application:
    name: festabook
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop # TODO: 추후 운영 환경에서 변경 필요
    defer-datasource-initialization: true
  profiles:
    include: secret

# Swagger
springdoc:
  swagger-ui:
    path: /api-docs
    persist-authorization: true

firebase:
  adminsdk:
    account:
      path: classpath:firebase/firebase-adminsdk-account.json
