spring:
  application:
    name: festabook
  jpa:
    open-in-view: false
    defer-datasource-initialization: true

# Swagger
springdoc:
  swagger-ui:
    path: /api-docs
    persist-authorization: true
