server:
  port: 80
  servlet:
    context-path: /api
  shutdown: graceful
  forward-headers-strategy: native
  tomcat:
    mbeanregistry:
      enabled: true

spring:
  application:
    name: festabook
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create-drop # TODO: 추후 운영 환경에서 변경 필요
    defer-datasource-initialization: true
  profiles:
    include: secret
  lifecycle:
    # WAS 종료 대기 시간 15초로 설정
    timeout-per-shutdown-phase: 15s

# Swagger
springdoc:
  swagger-ui:
    path: /api-docs
    persist-authorization: true
    operations-sorter: method

firebase:
  adminsdk:
    account:
      path: classpath:firebase/firebase-adminsdk-account.json

storage:
  image:
    max-size: 10485760 # 10 * 1024 * 1024, 10MB
