name: Backend CD Dev Server

on:
  push:
    branches: [ backend ]
    paths: [ 'backend/**' ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: [self-hosted, dev-runner]

    steps:
      - name: Checkout project repository
        uses: actions/checkout@v4

      - name: Create application-secret.yml file
        run: |
          mkdir -p backend/src/main/resources
          echo "${{ secrets.DEV_SECRET_YML }}" > backend/src/main/resources/application-secret.yml

      - name: Create firebase-adminsdk-account.json file
        run: |
          mkdir -p backend/src/main/resources/firebase
          echo "${{ secrets.FIREBASE_ADMINSDK_ACCOUNT_KEY }}" > backend/src/main/resources/firebase/firebase-adminsdk-account.json

      - name: Gradle cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('backend/**/*.gradle*', 'backend/**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Gradle build
        run: |
          chmod +x ./gradlew
          sudo ./gradlew clean build
        working-directory: ./backend

      - name: Get build jar file info
        id: get_build_jar
        run: |
          BUILD_JAR_PATH=$(find ./backend/build/libs -name "*.jar" ! -name "*plain.jar" | head -n 1)
          echo "BUILD_JAR_PATH=${BUILD_JAR_PATH}" >> $GITHUB_OUTPUT
          echo "BUILD_JAR_NAME=$(basename ${BUILD_JAR_PATH})" >> $GITHUB_OUTPUT

      - name: Deploy to EC2
        env:
          DEV_BLUE_WAS_PORT: ${{ secrets.DEV_BLUE_WAS_PORT }}
        run: |
          # 0. WAS 포트
          WAS_PORT=${DEV_BLUE_WAS_PORT}

          # 1. 이전 WAS 종료 (Graceful Shutdown)
          echo "Stopping old Spring WAS..."
          PID=$(sudo lsof -t -i:${WAS_PORT} || true)
          if [ -n "$PID" ]; then
            echo "Found running process with PID: $PID. Sending SIGTERM."
            sudo kill -SIGTERM $PID
            # 프로세스 종료 대기
            for i in $(seq 1 20); do
              if ! sudo kill -0 $PID 2>/dev/null; then
                echo "Process $PID has terminated."
                break
              fi
              echo "Waiting for process $PID to terminate... ($i/20)"
              sleep 1
            done
            if sudo kill -0 $PID 2>/dev/null; then
              echo "Process $PID did not terminate gracefully. Forcing shutdown with SIGKILL."
              sudo kill -9 $PID
              sleep 3
            fi
          else
            echo "No process found on port ${WAS_PORT}."
          fi

          # 2. 이전 JAR 파일 삭제 및 빌드 JAR 파일 복사
          echo "Deleting old JAR files..."
          DEPLOY_DIRECTORY="/home/ubuntu/${{ github.event.repository.name }}/backend"
          echo "DEPLOY_DIRECTORY=${DEPLOY_DIRECTORY}"
          mkdir -p "${DEPLOY_DIRECTORY}"
          sudo find "${DEPLOY_DIRECTORY}" -maxdepth 1 -name "*.jar" -delete
          echo "Old JAR files deleted."

          BUILD_JAR_PATH="${{ steps.get_build_jar.outputs.BUILD_JAR_PATH }}"
          BUILD_JAR_NAME="${{ steps.get_build_jar.outputs.BUILD_JAR_NAME }}"
          DEPLOY_JAR_PATH="${DEPLOY_DIRECTORY}/${BUILD_JAR_NAME}"
          echo "BUILD_JAR_PATH=${BUILD_JAR_PATH}"
          echo "BUILD_JAR_NAME=${BUILD_JAR_NAME}"
          echo "DEPLOY_JAR_PATH=${DEPLOY_JAR_PATH}"
          sudo cp "${BUILD_JAR_PATH}" "${DEPLOY_JAR_PATH}"
          echo "New JAR file copied."

          # 3. 새로운 WAS 실행
          echo "Starting new Spring WAS..."
          LOG_PATH="${DEPLOY_DIRECTORY}/application.log"
          echo "LOG_PATH=${LOG_PATH}"

          sudo nohup java -jar -Duser.timezone=Asia/Seoul "${DEPLOY_JAR_PATH}" --spring.profiles.active=dev --server.port=${WAS_PORT} &
          for i in $(seq 1 30); do
            if sudo lsof -t -i:${WAS_PORT} > /dev/null; then
              echo "WAS has started and is listening on port ${WAS_PORT}."
              break
            fi
            echo "Waiting for port ${WAS_PORT} to be occupied... ($i/30)"
            sleep 1
          done

          NEW_WAS_PID=$(sudo lsof -t -i:${WAS_PORT} || true)
          if [ -n "$NEW_WAS_PID" ]; then
            echo "Application started with PID: $NEW_WAS_PID."
          else
            echo "Error: Application failed to start."
          fi
          echo "Deployment complete."
