name: Frontend Deploy

on:
  pull_request:
    branches:
      - frontend
  push:
    branches:
      - frontend

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      # 1. 프로젝트 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v4

      # Node.js 20 설정
      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './frontend/package-lock.json'

      # 의존성 설치
      - name: Install dependencies
        run: npm ci
        working-directory: ./frontend

      # Vite로 빌드
      - name: Build with Vite
        run: npx vite build
        working-directory: ./frontend

      # SSH를 통해 기존 배포 파일 삭제
      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            REMOTE_APP_DIR="/home/${{ secrets.SSH_USERNAME }}/${{ github.event.repository.name }}/static"
            mkdir -p "${REMOTE_APP_DIR}"
            rm -rf "${REMOTE_APP_DIR}"

      # 빌드 파일 서버로 전송
      - name: SCP build files to remote server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          source: "frontend/dist"
          target: "/home/${{ secrets.SSH_USERNAME }}/${{ github.event.repository.name }}/static"

      # 3. aws-actions/configure-aws-credentials 액션을 사용하여 AWS 자격 증명 설정
      - name: Configure AWS credentials from EC2 Role
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}

      # 빌드 파일 S3에 업로드
      - name: Upload build files to S3
        run: |
          aws s3 cp ./frontend/dist ${{ secrets.S3_BUCKET }} --recursive

