name: Frontend Deploy

on:
  push:
    branches:
      - frontend

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 프로젝트 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v4

      # Node.js 20 설정
      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: './frontend/package-lock.json'

      # 의존성 설치
      - name: Install dependencies
        run: npm ci
        working-directory: ./frontend

      # Vite로 빌드
      - name: Build with Vite
        run: npx vite build
        working-directory: ./frontend

      # 기존의 배포 파일 삭제
      - name: Deploy to server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            REMOTE_APP_DIR="/home/${{ secrets.SSH_USERNAME }}/${{ github.event.repository.name }}/static"
            rm -rf "${REMOTE_APP_DIR}"

      # 빌드 파일 전송
      - name: SCP build files to remote server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          port: ${{ secrets.SSH_PORT }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          source: "frontend/dist"
          target: "/home/${{ secrets.SSH_USERNAME }}/${{ github.event.repository.name }}/static"

