name: Frontend CI/CD Dev

on:
  push:
    branches: [ frontend-dev ]
    paths: [ 'frontend/**' ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: [self-hosted]

    steps:
      # 작업 환경의 권한을 변경
      - name: Initialize workspace permissions
        run: |
          sudo chown -R ubuntu:ubuntu /home/ubuntu/actions-runner/_work

      # 프로젝트 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v4

      # 환경 변수 주입
      - name: Create .env.production
        run: |
          echo "VITE_API_HOST=${{ secrets.DEV_API_HOST }}" > ./frontend/.env.production

      # 의존성 설치
      - name: Install dependencies
        run: npm ci
        working-directory: ./frontend

      # Vite로 빌드
      - name: Build with Vite
        run: npx vite build
        working-directory: ./frontend

      # 빌드 파일 /home/ubuntu/2025-festabook/static/frontend/dist 이동
      # 이미지 저장 경로 디렉토리 생성 /home/ubuntu/2025-festabook/static/images
      - name: Move build files
        run: |
          DEPLOY_PATH="/home/ubuntu/2025-festabook/static/frontend"
          BUILD_DIST_PATH="./frontend/dist/"
          LOCAL_IMAGES_PATH="/home/ubuntu/2025-festabook/static/images"
          
          # 기존 빌드 파일 삭제
          sudo rm -rf "${DEPLOY_PATH}"

          # 디렉토리 생성
          sudo mkdir -p "${DEPLOY_PATH}"
          sudo mkdir -p "${LOCAL_IMAGES_PATH}"

          # 빌드 결과물 이동
          sudo cp -r "${BUILD_DIST_PATH}" "${DEPLOY_PATH}"
          sudo chmod -R 755 "${DEPLOY_PATH}"

          echo "Build files moved to ${DEPLOY_PATH}."
